language: php

php:
  - 7.2

cache:
  directories:
    - vendor

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-progress --prefer-dist --no-interaction --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - composer dump-auto
  - php artisan config:clear
  - php artisan cache:clear
  - php artisan route:clear
  - php artisan view:clear
  - php artisan module:list
  - php artisan route:list | grep users

before_install:
  - sudo apt-get update
  - mysql -e 'CREATE DATABASE travis_test_db;'
  - git submodule update --init --recursive

script:
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

services:
  - mysql

branches:
  only:
    - master

notifications:
  email: false

after_success:
  - travis_retry php ./vendor/bin/php-coveralls
