language: php

php:
  - 7.2

services:
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: deb https://packages.cloudfoundry.org/debian stable main
        key_url: https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key
    packages:
      - mysql-server
      - cf-cli

dist: trusty

branches:
  only:
    - master

cache:
  directories:
    - vendor

install:
  - cp .env.travis .env
  - mysql -e 'create database test;'
  - composer selfupdate
  - composer install --ignore-platform-reqs --no-interaction

matrix:
  allow_failures:
    - php: 7.2

script:
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php ./vendor/bin/php-coveralls
