language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-progress --prefer-dist --no-interaction --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - php artisan module:seed Roles
  - composer dump-nameauto
  - php artisan config:clear
  - php artisan cache:clear
  - php artisan route:clear
  - php artisan view:clear

before_install:
  - sudo apt-get update
  - mysql -e 'CREATE DATABASE travis_test_db;'
  - git submodule update --init --recursive

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpcs --extensions=php -s
  - ./vendor/bin/phpunit --debug --colors --coverage-text --coverage-clover build/logs/clover.xml

services:
  - mysql

branches:
  only:
    - master

notifications:
  email: false

after_success:
  - travis_retry php ./vendor/bin/php-coveralls -v
